Repository HYF-Class21/home, pull requests merged in 2023-03, with the labels that each got.

#10 XinGitLou
  package-lock.json
  student-bios/XinGitLou.md
  student-bios/img/IMG-0602.jpg
Labels: md

#19 Addi's bio
  student-bios/AddiAlomoush.md
Labels: md

#28 Add Neha Bio
  README.md
  student-bios/Neha-2012.md
  student-bios/img/Neha.jpg
Labels: md

#25 Alex
  student-bios/alex-maletskyi.md
  student-bios/img/instapic.jpg
Labels: md

#22 alisanlibioupdate
  student-bios/alisanlibio.md
  student-bios/img/alisanli.jpeg
Labels: md

#30 Added Marina's bio.
  student-bios/img/marina.jpg
  student-bios/marina.md
Labels: md

#32 Fix README workflows deliverables board link
  README.md
Labels: md

#33 Fix readme workflows deliverables board link
  README.md
Labels: md

#43 renamed bio file to match github account
  student-bios/marina-bashlak.md
Labels: md

#31 Add Juan student's bio
  package-lock.json
  package.json
  student-bios/README.md
  student-bios/alisanliibio.md
  student-bios/img/profile juan.jpg
  student-bios/jialvaradob.md
Labels: md

#37 Add Allan's student bio
  assets/IMG_0903.jpg
  student-bios/AllanSaku.md
Labels: md

#48 fix lint error: AllanSaku
  student-bios/AllanSaku.md
Labels: bug, md

#60 README.md: Fix deliverables links
  README.md
  admin/learners.yml
Labels: bug

#55 ¨belkisbio¨
  student-bios/belkisbio.md
Labels: check-in, student-bio
